version: "3.9"

x-restart-policy: &restart_policy
  restart: unless-stopped

x-logging: &default_logging
  options:
    max-size: "10m"
    max-file: "5"

services:
  postgres:
    image: postgres:16-alpine
    container_name: ${PROJECT_NAME}_postgres
    <<: *restart_policy
    user: "999:999"
    cap_drop:
      - ALL
    pids_limit: 200
    mem_limit: 1g
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - ./configs/postgres/init:/docker-entrypoint-initdb.d:ro
    networks:
      - backbone_net
      - azoth_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 20s
      timeout: 5s
      retries: 5
    logging: *default_logging
    security_opt:
      - no-new-privileges:true

  redis:
    image: redis:7-alpine
    container_name: ${PROJECT_NAME}_redis
    <<: *restart_policy
    user: "999:999"
    pids_limit: 150
    mem_limit: 512m
    command: ["sh", "-c", "if [ -n \"${REDIS_PASSWORD}\" ]; then exec redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}; else exec redis-server --appendonly yes; fi"]
    volumes:
      - redis_data:/data:Z
    networks:
      - backbone_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s
      retries: 5
    cap_drop:
      - ALL
    logging: *default_logging
    security_opt:
      - no-new-privileges:true

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: ${PROJECT_NAME}_mosquitto
    <<: *restart_policy
    user: "1883:1883"
    cap_drop:
      - ALL
    pids_limit: 100
    mem_limit: 256m
    ports:
      - "127.0.0.1:${MOSQUITTO_PORT:-1883}:1883"
      - "127.0.0.1:${MQTT_TLS_PORT:-8883}:8883"
    volumes:
      - ./configs/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./configs/mqtt/acl:/mosquitto/config/acl:ro
      - ./configs/mqtt/passwords:/mosquitto/config/passwords:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - backbone_net
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-h", "localhost", "-p", "1883", "-t", "health", "-C", "1", "-W", "3"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging: *default_logging
    security_opt:
      - no-new-privileges:true

  n8n:
    image: n8nio/n8n:1.74.1
    container_name: ${PROJECT_NAME}_n8n
    <<: *restart_policy
    user: "${LOCAL_UID}:${LOCAL_GID}"
    pids_limit: 300
    mem_limit: 1g
    ports:
      - "127.0.0.1:${N8N_PORT:-5678}:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: ${POSTGRES_PORT_INTERNAL:-5432}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_SECURE_COOKIE: ${N8N_SECURE_COOKIE}
      N8N_DIAGNOSTICS_ENABLED: "false"
      NODE_ENV: production
      WEBHOOK_URL: http://localhost:${N8N_WEBHOOK_PORT:-5679}
      GENERIC_TIMEZONE: ${TZ}
    depends_on:
      - postgres
      - redis
    volumes:
      - n8n_data:/home/node/.n8n
    tmpfs:
      - /tmp
    networks:
      - backbone_net
      - azoth_net
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5678/healthz')"]
      interval: 30s
      timeout: 5s
      retries: 5
    cap_drop:
      - ALL
    logging: *default_logging
    security_opt:
      - no-new-privileges:true

  grafana:
    image: grafana/grafana:10.4.3
    container_name: ${PROJECT_NAME}_grafana
    <<: *restart_policy
    user: "472"
    pids_limit: 200
    mem_limit: 512m
    ports:
      - "127.0.0.1:${GRAFANA_PORT:-3000}:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_INSTALL_PLUGINS: ""
      GF_SERVER_ROOT_URL: "http://localhost:${GRAFANA_PORT:-3000}"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring_net
    cap_drop:
      - ALL
    logging: *default_logging
    security_opt:
      - no-new-privileges:true

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: ${PROJECT_NAME}_prometheus
    <<: *restart_policy
    cap_drop:
      - ALL
    pids_limit: 200
    mem_limit: 1g
    ports:
      - "127.0.0.1:${PROMETHEUS_PORT:-9090}:9090"
    command: ["--config.file=/etc/prometheus/prometheus.yml", "--web.enable-lifecycle"]
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - monitoring_net
    logging: *default_logging
    security_opt:
      - no-new-privileges:true

  qdrant:
    image: qdrant/qdrant:v1.8.5
    container_name: ${PROJECT_NAME}_qdrant
    <<: *restart_policy
    cap_drop:
      - ALL
    pids_limit: 200
    mem_limit: 1g
    ports:
      - "127.0.0.1:${QDRANT_PORT:-6333}:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - koff_net
      - backbone_net
    logging: *default_logging
    security_opt:
      - no-new-privileges:true

  minio:
    image: quay.io/minio/minio:RELEASE.2024-06-18T01-10-18Z
    container_name: ${PROJECT_NAME}_minio
    <<: *restart_policy
    command: server /data --console-address ":9001"
    cap_drop:
      - ALL
    pids_limit: 200
    mem_limit: 1g
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:${MINIO_API_PORT:-9000}:9000"
      - "127.0.0.1:${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - minio_data:/data
    networks:
      - backbone_net
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging: *default_logging
    security_opt:
      - no-new-privileges:true

  strudel:
    image: ${STRUDEL_IMAGE:-ghcr.io/strudel-cc/strudel:0.10.0}
    container_name: ${PROJECT_NAME}_strudel
    <<: *restart_policy
    cap_drop:
      - ALL
    pids_limit: 200
    mem_limit: 512m
    ports:
      - "127.0.0.1:${STRUDEL_PORT:-7000}:7000"
    environment:
      TZ: ${TZ}
    networks:
      - maximus_net
      - ingress_net
    logging: *default_logging
    security_opt:
      - no-new-privileges:true

  ai-proxy:
    image: python:3.11-alpine
    container_name: ${PROJECT_NAME}_ai_proxy
    <<: *restart_policy
    command: ["sh", "-c", "python -m http.server 8081"]
    ports:
      - "127.0.0.1:${AI_PROXY_PORT:-8081}:8081"
    read_only: true
    cap_drop:
      - ALL
    pids_limit: 100
    mem_limit: 256m
    networks:
      - koff_net
      - ingress_net
    logging: *default_logging
    security_opt:
      - no-new-privileges:true

  embed-service:
    image: python:3.11-alpine
    container_name: ${PROJECT_NAME}_embed_service
    <<: *restart_policy
    command: ["sh", "-c", "python -m http.server 8082"]
    ports:
      - "127.0.0.1:${EMBED_SERVICE_PORT:-8082}:8082"
    read_only: true
    cap_drop:
      - ALL
    pids_limit: 100
    mem_limit: 256m
    networks:
      - koff_net
      - ingress_net
    logging: *default_logging
    security_opt:
      - no-new-privileges:true

networks:
  backbone_net:
    driver: bridge
  monitoring_net:
    driver: bridge
    internal: true
  ingress_net:
    driver: bridge
  azoth_net:
    driver: bridge
    internal: true
  maximus_net:
    driver: bridge
  koff_net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  mosquitto_data:
  mosquitto_log:
  n8n_data:
  grafana_data:
  prometheus_data:
  qdrant_data:
  minio_data:
